import React from "react";
import { BookOpen, Database, Milestone, ShieldCheck, Cpu, Smartphone, Code2, ShieldAlert, CheckCircle, Copy } from "lucide-react";

const dartServiceCode = `import 'package:cloud_firestore/cloud_firestore.dart';

class DatabaseService {
  final FirebaseFirestore _db = FirebaseFirestore.instance;

  // 1. Fetch academic class notes (sorted by date descending)
  Future<List<Map<String, dynamic>>> fetchNotes() async {
    try {
      QuerySnapshot querySnapshot = await _db
          .collection('notes')
          .orderBy('date', descending: true)
          .get();
      return querySnapshot.docs
          .map((doc) => {
                'id': doc.id,
                ...doc.data() as Map<String, dynamic>,
              })
          .toList();
    } catch (e) {
      print("Error fetching notes from Firestore: \$e");
      rethrow;
    }
  }

  // 2. Fetch active verified corporate internships
  Future<List<Map<String, dynamic>>> fetchInternships() async {
    try {
      QuerySnapshot querySnapshot = await _db
          .collection('internships')
          .orderBy('lastDate', descending: false)
          .get();
      return querySnapshot.docs
          .map((doc) => {
                'id': doc.id,
                ...doc.data() as Map<String, dynamic>,
              })
          .toList();
    } catch (e) {
      print("Error fetching internships: \$e");
      rethrow;
    }
  }

  // 3. Fetch verified preparation assessment portal links
  Future<List<Map<String, dynamic>>> fetchCompanyLinks() async {
    try {
      QuerySnapshot querySnapshot = await _db
          .collection('company_links')
          .get();
      return querySnapshot.docs
          .map((doc) => {
                'id': doc.id,
                ...doc.data() as Map<String, dynamic>,
              })
          .toList();
    } catch (e) {
      print("Error fetching company links: \$e");
      rethrow;
    }
  }
}`;

const dartMainCode = `import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Auto-generated by FlutterFire CLI

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  // Initializing the Firebase layer safely
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  
  runApp(const MaterialApp(
    debugShowCheckedModeBanner: false,
    home: DepartmentDashboard(),
  ));
}`;

const flutterUiCode = `import 'package:flutter/material.dart';
import 'database_service.dart';

class AcademicNotesPage extends StatefulWidget {
  const AcademicNotesPage({Key? key}) : super(key: key);

  @override
  State<AcademicNotesPage> createState() => _AcademicNotesPageState();
}

class _AcademicNotesPageState extends State<AcademicNotesPage> {
  final DatabaseService _db = DatabaseService();
  late Future<List<Map<String, dynamic>>> _notesFuture;

  @override
  void initState() {
    super.initState();
    // Cache future in initState to avoid redundant database calls on re-renders
    _notesFuture = _db.fetchNotes();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Department Lecture Notes'),
        backgroundColor: Colors.teal[800],
      ),
      body: FutureBuilder<List<Map<String, dynamic>>>(
        future: _notesFuture,
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.waiting) {
            return const Center(child: CircularProgressIndicator());
          } else if (snapshot.hasError) {
            return Center(child: Text('Integration error: \${snapshot.error}'));
          } else if (!snapshot.hasData || snapshot.data!.isEmpty) {
            return const Center(child: Text('No notes published yet.'));
          }

          final notes = snapshot.data!;
          return ListView.builder(
            itemCount: notes.length,
            padding: const EdgeInsets.symmetric(vertical: 12),
            itemBuilder: (context, index) {
              final note = notes[index];
              return Card(
                elevation: 2,
                margin: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
                child: ListTile(
                  leading: const Icon(Icons.class_, color: Colors.teal),
                  title: Text(note['title'] ?? 'No Title'),
                  subtitle: Text("\${note['subject']} • \${note['semester']}"),
                  trailing: const Icon(Icons.arrow_forward_ios, size: 14),
                  onTap: () {
                    // Action handler...
                  },
                ),
              );
            },
          );
        },
      ),
    );
  }
}`;

const flutterWebviewCode = `import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

class WebViewPage extends StatefulWidget {
  final String url;
  final String title;

  const WebViewPage({Key? key, required this.url, required this.title}) : super(key: key);

  @override
  State<WebViewPage> createState() => _WebViewPageState();
}

class _WebViewPageState extends State<WebViewPage> {
  late final WebViewController _controller;
  bool _isLoading = true;

  @override
  void initState() {
    super.initState();
    _controller = WebViewController()
      ..setJavaScriptMode(JavaScriptMode.unrestricted)
      ..setBackgroundColor(const Color(0x00000000))
      ..setNavigationDelegate(
        NavigationDelegate(
          onPageStarted: (String url) {
            setState(() {
              _isLoading = true;
            });
          },
          onPageFinished: (String url) {
            setState(() {
              _isLoading = false;
            });
          },
        ),
      )
      ..loadRequest(Uri.parse(widget.url));
  }

  @override
  Widget build(BuildContext context) {
    return WillPopScope(
      onWillPop: () async {
        if (await _controller.canGoBack()) {
          await _controller.goBack();
          return false; // Prevent closing the route if we can navigate back in history
        }
        return true; // Let standard route pop happen
      },
      child: Scaffold(
        appBar: AppBar(
          title: Text(widget.title),
          backgroundColor: Colors.teal[900],
        ),
        body: Stack(
          children: [
            WebViewWidget(controller: _controller),
            if (_isLoading)
              const Center(
                child: CircularProgressIndicator(color: Colors.teal),
              ),
          ],
        ),
      ),
    );
  }
}`;

const firestoreRulesCode = `rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    
    function isAuthenticated() {
      return request.auth != null;
    }
    
    function isFaculty() {
      return isAuthenticated() && 
        get(/databases/\$(database)/documents/users/\$(request.auth.uid)).data.role == 'faculty';
    }

    // 1. Authenticated users can read notes and internships. Only faculty can write/update.
    match /notes/{noteId} {
      allow read: if isAuthenticated();
      allow write, update, delete: if isFaculty();
    }

    match /internships/{internshipId} {
      allow read: if isAuthenticated();
      allow write, update, delete: if isFaculty();
    }

    match /company_links/{linkId} {
      allow read: if isAuthenticated();
      allow write, update, delete: if isFaculty();
    }

    // 2. Prevent unauthorized access to the 'users' collection.
    match /users/{userId} {
      allow read: if isAuthenticated();
      allow create: if isAuthenticated() && request.auth.uid == userId && request.resource.data.role == 'student';
      allow update: if isAuthenticated() && request.auth.uid == userId && request.resource.data.role == resource.data.role; // Prevent self-role elevation
      allow delete: if false; // Denied deletion
    }
  }
}`;

export default function ArchitectureDocs() {
  const [activeTab, setActiveTab] = React.useState<"arch" | "schema" | "roadmap" | "security" | "flutter">("arch");
  const [flutterModule, setFlutterModule] = React.useState<"service" | "nav" | "webview" | "rules">("service");
  const [simulatedRole, setSimulatedRole] = React.useState<"faculty" | "student" | "guest">("student");
  const [copiedState, setCopiedState] = React.useState<string | null>(null);

  const handleCopy = (text: string, moduleName: string) => {
    navigator.clipboard.writeText(text);
    setCopiedState(moduleName);
    setTimeout(() => setCopiedState(null), 2000);
  };

  return (
    <div className="bg-white border-4 border-black shadow-[6px_6px_0px_0px_rgba(0,0,0,1)] overflow-hidden" id="architecture-docs">
      {/* Doc Header */}
      <div className="p-6 border-b-4 border-black bg-black text-white">
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
          <div className="flex items-center gap-3">
            <BookOpen className="h-6 w-6 text-[#00FF00]" />
            <div>
              <h2 className="text-2xl font-black uppercase tracking-tight">System Specifications & Architecture</h2>
              <p className="text-xs text-slate-400 font-mono uppercase tracking-widest mt-0.5">COLLEGE LEDGER & COMPLIANCE BLUEPRINT</p>
            </div>
          </div>
        </div>

        {/* Tab Selector */}
        <div className="flex gap-2 mt-6 overflow-x-auto pb-1 scrollbar-none">
          <button
            onClick={() => setActiveTab("arch")}
            className={`flex items-center gap-2 px-4 py-2 border-2 border-black text-xs font-black uppercase tracking-wider transition-all shrink-0 ${
              activeTab === "arch"
                ? "bg-[#00FF00] text-black border-[#00FF00]"
                : "bg-slate-900 text-slate-300 hover:bg-slate-800"
            }`}
          >
            <Cpu className="h-4 w-4" /> System Architecture
          </button>
          <button
            onClick={() => setActiveTab("schema")}
            className={`flex items-center gap-2 px-4 py-2 border-2 border-black text-xs font-black uppercase tracking-wider transition-all shrink-0 ${
              activeTab === "schema"
                ? "bg-[#00FF00] text-black border-[#00FF00]"
                : "bg-slate-900 text-slate-300 hover:bg-slate-800"
            }`}
          >
            <Database className="h-4 w-4" /> Database Schema
          </button>
          <button
            onClick={() => setActiveTab("roadmap")}
            className={`flex items-center gap-2 px-4 py-2 border-2 border-black text-xs font-black uppercase tracking-wider transition-all shrink-0 ${
              activeTab === "roadmap"
                ? "bg-[#00FF00] text-black border-[#00FF00]"
                : "bg-slate-900 text-slate-300 hover:bg-slate-800"
            }`}
          >
            <Milestone className="h-4 w-4" /> MVP Roadmap
          </button>
          <button
            onClick={() => setActiveTab("security")}
            className={`flex items-center gap-2 px-4 py-2 border-2 border-black text-xs font-black uppercase tracking-wider transition-all shrink-0 ${
              activeTab === "security"
                ? "bg-[#00FF00] text-black border-[#00FF00]"
                : "bg-slate-900 text-slate-300 hover:bg-slate-800"
            }`}
          >
            <ShieldCheck className="h-4 w-4" /> Best Practices
          </button>
          <button
            onClick={() => setActiveTab("flutter")}
            className={`flex items-center gap-2 px-4 py-2 border-2 border-black text-xs font-black uppercase tracking-wider transition-all shrink-0 ${
              activeTab === "flutter"
                ? "bg-[#00FF00] text-black border-[#00FF00]"
                : "bg-slate-900 text-slate-300 hover:bg-slate-800"
            }`}
          >
            <Smartphone className="h-4 w-4" /> Flutter Companion SDK
          </button>
        </div>
      </div>

      {/* Doc Content */}
      <div className="p-6 max-h-[550px] overflow-y-auto">
        {activeTab === "arch" && (
          <div className="space-y-6">
            <div>
              <h3 className="text-xl font-black uppercase tracking-tight text-black flex items-center gap-2">
                <Cpu className="h-5 w-5 text-black" /> System Architecture Design
              </h3>
              <p className="text-gray-700 mt-2 text-sm leading-relaxed">
                Smart Entry utilizes a robust, mobile-optimized decoupled client-server architecture.
                Designed with progressive enhancement, it guarantees frictionless offline capabilities and rapid responses for student users on mobile networks.
              </p>
            </div>

            {/* Visual Architecture Representation */}
            <div className="bg-slate-50 p-4 border-2 border-black font-mono text-xs text-slate-800 space-y-2">
              <div className="font-black text-black border-b-2 border-black pb-2 mb-2 uppercase">FLOW ARCHITECTURE DIAGRAM</div>
              <div className="flex flex-col gap-2">
                <div className="p-2.5 bg-white border-2 border-black shadow-[2px_2px_0px_0px_rgba(0,0,0,1)]">
                  📱 <span className="font-black uppercase">Client Layer (React.js + Tailwind CSS)</span>
                  <p className="text-[11px] text-gray-500 mt-1 uppercase">Multi-role views (Student / CR / Admin) with optimistic offline UI & responsive touch targets.</p>
                </div>
                <div className="text-center text-black font-black">⬇ API GATEWAY (HTTPS / REST) ⬆</div>
                <div className="p-2.5 bg-white border-2 border-black shadow-[2px_2px_0px_0px_rgba(0,0,0,1)]">
                  ⚙️ <span className="font-black uppercase">Application Services (Express Node.js Middleware)</span>
                  <p className="text-[11px] text-gray-500 mt-1 uppercase">Role-Based Access Control (RBAC), secure file validation (screenshot sanitizer), and CSV payload generator.</p>
                </div>
                <div className="text-center text-black font-black">⬇ PERSISTENCE CONNECTOR ⬆</div>
                <div className="p-2.5 bg-white border-2 border-black shadow-[2px_2px_0px_0px_rgba(0,0,0,1)]">
                  💾 <span className="font-black uppercase">Durable Persistence (Google Cloud Firestore / SQL)</span>
                  <p className="text-[11px] text-gray-500 mt-1 uppercase">Real-time collections mapping student contributions, authorized CR permissions, events, and notices securely.</p>
                </div>
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="p-4 border-2 border-black bg-slate-50">
                <h4 className="font-black uppercase text-sm">Key Client Features</h4>
                <ul className="text-xs text-slate-700 list-disc list-inside mt-2 space-y-1 font-mono">
                  <li>PWA (Progressive Web App) manifest configuration capability</li>
                  <li>Base64 local image encoding (zero cloud bucket lag)</li>
                  <li>Responsive touch elements (min 44px)</li>
                  <li>Real-time role switching panel (simulation)</li>
                </ul>
              </div>
              <div className="p-4 border-2 border-black bg-slate-50">
                <h4 className="font-black uppercase text-sm">Key Security Gateways</h4>
                <ul className="text-xs text-slate-700 list-disc list-inside mt-2 space-y-1 font-mono">
                  <li>Strict server-side Role-Based Access Control</li>
                  <li>Payload sanitization & base64 size caps</li>
                  <li>Atomic state-locking (approved transactions cannot be spoofed)</li>
                  <li>Verified email and register number bindings</li>
                </ul>
              </div>
            </div>
          </div>
        )}

        {activeTab === "schema" && (
          <div className="space-y-6">
            <div>
              <h3 className="text-xl font-black uppercase tracking-tight text-black flex items-center gap-2">
                <Database className="h-5 w-5 text-black" /> Relational & Document Schema
              </h3>
              <p className="text-gray-700 mt-2 text-sm">
                The database is structured to seamlessly support both Document-based (NoSQL Firestore) and Relational (PostgreSQL) options. Below is the strict structural schema definition.
              </p>
            </div>

            {/* Schema Models */}
            <div className="space-y-4">
              {/* Users Schema */}
              <div className="p-4 border-2 border-black bg-slate-50">
                <div className="flex items-center justify-between border-b border-black pb-2 mb-2">
                  <span className="font-black text-black font-mono text-xs uppercase">👤 Table: Users</span>
                  <span className="text-[10px] bg-black text-white px-2 py-0.5 font-mono uppercase font-black">RBAC Source</span>
                </div>
                <pre className="text-xs text-slate-700 font-mono overflow-x-auto">
{`{
  id: string;        // Primary Key (e.g., Auth UID)
  name: string;      // Full student or staff name
  regNo: string;     // Unique Roll No / Registration No (Index)
  role: string;      // "admin" | "cr" | "student"
  email: string;     // College institutional email
}`}
                </pre>
              </div>

              {/* Transactions Schema */}
              <div className="p-4 border-2 border-black bg-slate-50">
                <div className="flex items-center justify-between border-b border-black pb-2 mb-2">
                  <span className="font-black text-black font-mono text-xs uppercase">💰 Table: Transactions</span>
                  <span className="text-[10px] bg-black text-white px-2 py-0.5 font-mono uppercase font-black">Ledger</span>
                </div>
                <pre className="text-xs text-slate-700 font-mono overflow-x-auto">
{`{
  id: string;            // Primary Key (Unique ledger entry)
  studentName: string;   // Redundant copy for fast read performance
  regNo: string;         // Foreign Key -> Users.regNo (Index)
  amount: number;        // Contribution amount (double precision)
  purpose: string;       // Foreign Key reference or description
  timestamp: string;     // ISO timestamp (defaults to server current time)
  status: string;        // "Pending" | "Approved" | "Rejected"
  screenshotUrl: string; // Sanitized base64 string or file storage URL
  notes: string;         // Comments from CR verification (Optional)
}`}
                </pre>
              </div>

              {/* Events & Notices */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="p-4 border-2 border-black bg-slate-50">
                  <span className="block font-black text-black font-mono text-xs border-b border-black pb-2 mb-2 uppercase">📅 Table: Events</span>
                  <pre className="text-[11px] text-slate-700 font-mono overflow-x-auto">
{`{
  id: string;
  title: string;
  type: string; // academic/iv/deadline/holiday
  date: string; // YYYY-MM-DD
  description: string;
  createdBy: string;
}`}
                  </pre>
                </div>
                <div className="p-4 border-2 border-black bg-slate-50">
                  <span className="block font-black text-black font-mono text-xs border-b border-black pb-2 mb-2 uppercase">📢 Table: Notices</span>
                  <pre className="text-[11px] text-slate-700 font-mono overflow-x-auto">
{`{
  id: string;
  title: string;
  content: string;
  date: string; // ISO
  createdBy: string;
  priority: string; // high/medium/low
}`}
                  </pre>
                </div>
              </div>
            </div>
          </div>
        )}

        {activeTab === "roadmap" && (
          <div className="space-y-6">
            <div>
              <h3 className="text-xl font-black uppercase tracking-tight text-black flex items-center gap-2">
                <Milestone className="h-5 w-5 text-black" /> Development Roadmap (MVP to Release)
              </h3>
              <p className="text-gray-700 mt-2 text-sm">
                A structured 4-phase agile pipeline starting from a Minimum Viable Product (MVP) up to wide college scaling.
              </p>
            </div>

            <div className="space-y-4 relative border-l-4 border-black pl-6 ml-3">
              {/* Milestone 1 */}
              <div className="relative">
                <span className="absolute -left-[32px] top-1.5 flex h-4 w-4 items-center justify-center bg-[#00FF00] border-2 border-black"></span>
                <h4 className="font-black uppercase text-gray-900 text-sm">Phase 1: Local Ledger & Calendar MVP (Current Build)</h4>
                <p className="text-[11px] font-mono text-gray-500 uppercase">Focus: Core Ledger logic, responsive design & calendar widget</p>
                <ul className="text-xs text-gray-700 list-disc list-inside mt-2 space-y-1">
                  <li>Fully functional responsive Student/CR/Admin dashboards.</li>
                  <li>Base64 screenshot upload sandbox and CR approval gates.</li>
                  <li>Dynamic CSV financial statement exporter.</li>
                </ul>
              </div>

              {/* Milestone 2 */}
              <div className="relative">
                <span className="absolute -left-[32px] top-1.5 flex h-4 w-4 items-center justify-center bg-white border-2 border-black"></span>
                <h4 className="font-black uppercase text-gray-900 text-sm">Phase 2: Cloud Database & True Authentication Integration</h4>
                <p className="text-[11px] font-mono text-gray-500 uppercase">Focus: Secure server cloud migration</p>
                <ul className="text-xs text-gray-700 list-disc list-inside mt-2 space-y-1">
                  <li>Migrate internal memory system to Firebase Firestore / Cloud SQL.</li>
                  <li>Configure secure Google / Single Sign-On (SSO) with college domains.</li>
                  <li>Hardened Firestore Security Rules (ABAC validation helpers).</li>
                </ul>
              </div>

              {/* Milestone 3 */}
              <div className="relative">
                <span className="absolute -left-[32px] top-1.5 flex h-4 w-4 items-center justify-center bg-white border-2 border-black"></span>
                <h4 className="font-black uppercase text-gray-900 text-sm">Phase 3: Real-Time Notifications & PWA Manifest</h4>
                <p className="text-[11px] font-mono text-gray-500 uppercase">Focus: Dynamic user engagement and offline support</p>
                <ul className="text-xs text-gray-700 list-disc list-inside mt-2 space-y-1">
                  <li>Add push notification triggers when notices or event contributions are published.</li>
                  <li>PWA worker configuration to cache upcoming calendar events for offline view.</li>
                  <li>WhatsApp/SMS notification API integration for overdue fees.</li>
                </ul>
              </div>

              {/* Milestone 4 */}
              <div className="relative">
                <span className="absolute -left-[32px] top-1.5 flex h-4 w-4 items-center justify-center bg-white border-2 border-black"></span>
                <h4 className="font-black uppercase text-gray-900 text-sm">Phase 4: Full Campus Scale-out & Financial Audit Logging</h4>
                <p className="text-[11px] font-mono text-gray-500 uppercase">Focus: Compliance & Enterprise expansion</p>
                <ul className="text-xs text-gray-700 list-disc list-inside mt-2 space-y-1">
                  <li>Enable multi-department workspace isolation.</li>
                  <li>Integrate instant bank statement reconciliation via direct UPI merchant APIs.</li>
                  <li>Immutable audit-log stream for Staff verification to prevent any ledger tamper risks.</li>
                </ul>
              </div>
            </div>
          </div>
        )}

        {activeTab === "security" && (
          <div className="space-y-6">
            <div>
              <h3 className="text-xl font-black uppercase tracking-tight text-black flex items-center gap-2">
                <ShieldCheck className="h-5 w-5 text-black" /> Security Best Practices
              </h3>
              <p className="text-gray-700 mt-2 text-sm leading-relaxed">
                Student applications must handle personal information (names, grades, register numbers) and financials with high security. Follow these guidelines strictly during development:
              </p>
            </div>

            <div className="space-y-4">
              <div className="p-4 border-2 border-black bg-slate-50">
                <h4 className="font-black uppercase text-sm">1. Secure UPI ID / QR Management</h4>
                <p className="text-xs text-slate-800 mt-1 leading-relaxed">
                  Always sanitize the UPI ID inputs and strictly restrict UPI modifications to validated CRs or Staff. Reject any foreign scripts, cross-site elements, or fake payment redirect strings to prevent payment hijack attacks.
                </p>
              </div>

              <div className="p-4 border-2 border-black bg-slate-50">
                <h4 className="font-black uppercase text-sm">2. Anti-Spoofing Screenshot Verification</h4>
                <p className="text-xs text-slate-800 mt-1 leading-relaxed">
                  Ensure the backend restricts screenshot uploads to valid image mime types (PNG, JPEG). In advanced versions, implement OCR (Optical Character Recognition) on the server to auto-read the UPI Transaction Reference ID (UTR) and compare it against a verified spreadsheet to avoid double-spend or fake mockup uploads.
                </p>
              </div>

              <div className="p-4 border-2 border-black bg-slate-50">
                <h4 className="font-black uppercase text-sm">3. Principle of Least Privilege (RBAC)</h4>
                <p className="text-xs text-slate-800 mt-1 leading-relaxed">
                  CR actions (approving payments, changing UPI details) must require a valid authorization token verified by the server. Users must never be allowed to elevate their own permissions or edit transaction logs after approval.
                </p>
              </div>

              <div className="p-4 border-2 border-black bg-slate-50">
                <h4 className="font-black uppercase text-sm">4. Clear Data Purging Rules</h4>
                <p className="text-xs text-slate-800 mt-1 leading-relaxed">
                  Establish an auto-archiving policy where old screenshots are deleted after semester completion to respect storage boundaries and privacy standards (GDPR-friendly student directories).
                </p>
              </div>
            </div>
          </div>
        )}

        {activeTab === "flutter" && (
          <div className="space-y-6">
            <div className="bg-slate-900 text-[#00FF00] p-4 border-2 border-black font-mono text-xs">
              <div className="font-black text-white text-sm border-b border-white pb-2 mb-2 flex items-center justify-between">
                <span>📱 MOBILE SDK BLUEPRINT STUDIO</span>
                <span className="bg-emerald-500/20 text-emerald-400 border border-emerald-500/30 px-2 py-0.5 rounded text-[10px] animate-pulse">ACTIVE BLUEPRINT</span>
              </div>
              <p className="text-slate-300 text-xs leading-relaxed">
                Connect the React Web Portal with a cross-platform Flutter application using Google Firebase Firestore and client-side modern SDK modules. Select a module below to inspect full Dart source code, configure navigation layouts, and deploy security rules.
              </p>
            </div>

            {/* Sub Tabs Selection */}
            <div className="grid grid-cols-2 md:grid-cols-4 gap-2">
              {[
                { id: "service", label: "1. Database Service", icon: Database },
                { id: "nav", label: "2. Navigation & Loading", icon: Smartphone },
                { id: "webview", label: "3. WebView Wrapper", icon: Code2 },
                { id: "rules", label: "4. Security Rules", icon: ShieldCheck }
              ].map((sub) => (
                <button
                  key={sub.id}
                  onClick={() => setFlutterModule(sub.id as any)}
                  className={`flex flex-col items-center justify-center p-3 border-2 border-black font-black text-center text-xs transition-all uppercase tracking-tight ${
                    flutterModule === sub.id
                      ? "bg-black text-[#00FF00] shadow-[2px_2px_0px_0px_rgba(0,0,0,1)] translate-x-[-2px] translate-y-[-2px]"
                      : "bg-white text-black hover:bg-slate-100"
                  }`}
                >
                  <sub.icon className="h-4 w-4 mb-1" />
                  {sub.label}
                </button>
              ))}
            </div>

            {/* Selected Module Detail */}
            {flutterModule === "service" && (
              <div className="space-y-4">
                <div className="p-4 border-2 border-black bg-slate-50 relative">
                  <div className="flex justify-between items-center mb-3">
                    <h4 className="font-black uppercase text-sm flex items-center gap-2">
                      <Code2 className="h-5 w-5 text-emerald-600" />
                      Dart Database Service Class
                    </h4>
                    <button
                      onClick={() => handleCopy(dartServiceCode, "service")}
                      className="flex items-center gap-1.5 border-2 border-black bg-white px-2.5 py-1 text-xs font-black uppercase hover:bg-slate-100 active:translate-y-[1px]"
                    >
                      {copiedState === "service" ? (
                        <>
                          <CheckCircle className="h-3.5 w-3.5 text-emerald-600" />
                          Copied!
                        </>
                      ) : (
                        <>
                          <Copy className="h-3.5 w-3.5" />
                          Copy Dart Code
                        </>
                      )}
                    </button>
                  </div>
                  <p className="text-xs text-gray-600 mb-3 leading-relaxed">
                    This file (`database_service.dart`) uses async/await models to load verified notes, internships, and company links collections concurrently from the central repository database.
                  </p>
                  <div className="bg-slate-900 p-4 border-2 border-black rounded shadow-inner overflow-x-auto max-h-[300px]">
                    <pre className="text-xs text-slate-300 font-mono">
                      {dartServiceCode}
                    </pre>
                  </div>
                </div>

                <div className="p-4 border-2 border-black bg-slate-50">
                  <div className="flex justify-between items-center mb-2">
                    <h4 className="font-black uppercase text-xs">Flutter Main Bootloader (`main.dart`)</h4>
                    <button
                      onClick={() => handleCopy(dartMainCode, "main")}
                      className="text-xs text-blue-600 hover:underline flex items-center gap-1"
                    >
                      <Copy className="h-3 w-3" /> {copiedState === "main" ? "Copied" : "Copy Bootloader"}
                    </button>
                  </div>
                  <div className="bg-slate-900 p-4 border-2 border-black rounded shadow-inner overflow-x-auto">
                    <pre className="text-xs text-emerald-400 font-mono">
                      {dartMainCode}
                    </pre>
                  </div>
                </div>
              </div>
            )}

            {flutterModule === "nav" && (
              <div className="space-y-4">
                <div className="p-4 border-2 border-black bg-slate-50 relative">
                  <div className="flex justify-between items-center mb-3">
                    <h4 className="font-black uppercase text-sm flex items-center gap-2">
                      <Smartphone className="h-5 w-5 text-blue-600" />
                      InitState and FutureBuilder UI
                    </h4>
                    <button
                      onClick={() => handleCopy(flutterUiCode, "ui")}
                      className="flex items-center gap-1.5 border-2 border-black bg-white px-2.5 py-1 text-xs font-black uppercase hover:bg-slate-100 active:translate-y-[1px]"
                    >
                      {copiedState === "ui" ? (
                        <>
                          <CheckCircle className="h-3.5 w-3.5 text-emerald-600" />
                          Copied!
                        </>
                      ) : (
                        <>
                          <Copy className="h-3.5 w-3.5" />
                          Copy Widget Code
                        </>
                      )}
                    </button>
                  </div>
                  <p className="text-xs text-gray-600 mb-3 leading-relaxed">
                    Triggered by an `onPressed` card gesture, Flutter pushes a new context route. The screen subscribes to the service during `initState` to fetch live collections asynchronously, displaying items smoothly with responsive touch bounds.
                  </p>
                  <div className="bg-slate-900 p-4 border-2 border-black rounded shadow-inner overflow-x-auto max-h-[350px]">
                    <pre className="text-xs text-slate-300 font-mono">
                      {flutterUiCode}
                    </pre>
                  </div>
                </div>

                {/* Simulated Click Execution Flow */}
                <div className="border-2 border-black p-4 bg-white shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]">
                  <h4 className="font-black text-xs uppercase mb-2">Simulated Interactive Click Route Visualizer</h4>
                  <div className="grid grid-cols-1 md:grid-cols-3 gap-3 items-center">
                    <div className="p-3 border-2 border-dashed border-black bg-slate-50 text-center">
                      <div className="text-[10px] uppercase font-bold text-gray-400">Step 1: Dashboard</div>
                      <span className="inline-block mt-2 bg-blue-600 text-white text-xs font-bold px-3 py-1.5 rounded uppercase shadow">
                        Class Notes Card
                      </span>
                    </div>
                    <div className="text-center font-black text-xs">
                      👉 onPressed: Navigator.push()
                    </div>
                    <div className="p-3 border-2 border-dashed border-black bg-emerald-50 text-center">
                      <div className="text-[10px] uppercase font-bold text-gray-400">Step 2: Notes Page</div>
                      <span className="inline-block mt-2 bg-emerald-700 text-white text-xs font-bold px-3 py-1.5 rounded uppercase shadow">
                        FutureBuilder Loaded
                      </span>
                    </div>
                  </div>
                </div>
              </div>
            )}

            {flutterModule === "webview" && (
              <div className="space-y-4">
                <div className="p-4 border-2 border-black bg-slate-50 relative">
                  <div className="flex justify-between items-center mb-3">
                    <h4 className="font-black uppercase text-sm flex items-center gap-2">
                      <Code2 className="h-5 w-5 text-amber-600" />
                      webview_flutter 4.x wrapper page
                    </h4>
                    <button
                      onClick={() => handleCopy(flutterWebviewCode, "webview")}
                      className="flex items-center gap-1.5 border-2 border-black bg-white px-2.5 py-1 text-xs font-black uppercase hover:bg-slate-100 active:translate-y-[1px]"
                    >
                      {copiedState === "webview" ? (
                        <>
                          <CheckCircle className="h-3.5 w-3.5 text-emerald-600" />
                          Copied!
                        </>
                      ) : (
                        <>
                          <Copy className="h-3.5 w-3.5" />
                          Copy WebView Code
                        </>
                      )}
                    </button>
                  </div>
                  <p className="text-xs text-gray-600 mb-3 leading-relaxed">
                    Loads assessment or external links safely in a dedicated sandboxed screen. Enforces hardware-backed back-navigation handling via `WillPopScope` so students can navigate back inside the WebView history instead of popping back to the app immediately.
                  </p>
                  <div className="bg-slate-900 p-4 border-2 border-black rounded shadow-inner overflow-x-auto max-h-[350px]">
                    <pre className="text-xs text-slate-300 font-mono">
                      {flutterWebviewCode}
                    </pre>
                  </div>
                </div>
              </div>
            )}

            {flutterModule === "rules" && (
              <div className="space-y-4">
                <div className="p-4 border-2 border-black bg-slate-50 relative">
                  <div className="flex justify-between items-center mb-3">
                    <h4 className="font-black uppercase text-sm flex items-center gap-2">
                      <ShieldCheck className="h-5 w-5 text-rose-600" />
                      Firestore Security Rules (`firestore.rules`)
                    </h4>
                    <button
                      onClick={() => handleCopy(firestoreRulesCode, "rules")}
                      className="flex items-center gap-1.5 border-2 border-black bg-white px-2.5 py-1 text-xs font-black uppercase hover:bg-slate-100 active:translate-y-[1px]"
                    >
                      {copiedState === "rules" ? (
                        <>
                          <CheckCircle className="h-3.5 w-3.5 text-emerald-600" />
                          Copied!
                        </>
                      ) : (
                        <>
                          <Copy className="h-3.5 w-3.5" />
                          Copy Rules
                        </>
                      )}
                    </button>
                  </div>
                  <p className="text-xs text-gray-600 mb-3 leading-relaxed">
                    These absolute safety rules lock down unauthorized write requests. Only authenticated users with the verified role of <strong>faculty</strong> (stored securely inside the database users collection) can publish or modify materials. Students get read-only access.
                  </p>
                  <div className="bg-slate-900 p-4 border-2 border-black rounded shadow-inner overflow-x-auto">
                    <pre className="text-xs text-rose-400 font-mono">
                      {firestoreRulesCode}
                    </pre>
                  </div>
                </div>

                {/* Rules Interactive Tester Matrix */}
                <div className="border-2 border-black p-4 bg-slate-50 shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]">
                  <div className="flex justify-between items-center border-b border-black pb-2 mb-3">
                    <h4 className="font-black text-xs uppercase">Interactive Security Rules Simulator</h4>
                    <div className="flex gap-1.5">
                      {(["faculty", "student", "guest"] as const).map((role) => (
                        <button
                          key={role}
                          onClick={() => setSimulatedRole(role)}
                          className={`px-2 py-0.5 border text-[10px] font-mono capitalize ${
                            simulatedRole === role
                              ? "bg-black text-white font-bold border-black"
                              : "bg-white text-slate-600 hover:bg-slate-100 border-slate-300"
                          }`}
                        >
                          {role}
                        </button>
                      ))}
                    </div>
                  </div>

                  <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
                    <div className="p-3 border border-black bg-white">
                      <span className="text-[10px] font-mono font-bold text-slate-400">TARGET: /notes/</span>
                      <div className="mt-1 flex items-center justify-between text-xs font-mono">
                        <span>Read API</span>
                        <span className={`px-2 py-0.5 font-bold ${simulatedRole !== "guest" ? "text-emerald-700 bg-emerald-50" : "text-rose-700 bg-rose-50"}`}>
                          {simulatedRole !== "guest" ? "✔ ALLOW" : "❌ DENY"}
                        </span>
                      </div>
                      <div className="mt-1 flex items-center justify-between text-xs font-mono">
                        <span>Write API</span>
                        <span className={`px-2 py-0.5 font-bold ${simulatedRole === "faculty" ? "text-emerald-700 bg-emerald-50" : "text-rose-700 bg-rose-50"}`}>
                          {simulatedRole === "faculty" ? "✔ ALLOW" : "❌ DENY"}
                        </span>
                      </div>
                    </div>

                    <div className="p-3 border border-black bg-white">
                      <span className="text-[10px] font-mono font-bold text-slate-400">TARGET: /internships/</span>
                      <div className="mt-1 flex items-center justify-between text-xs font-mono">
                        <span>Read API</span>
                        <span className={`px-2 py-0.5 font-bold ${simulatedRole !== "guest" ? "text-emerald-700 bg-emerald-50" : "text-rose-700 bg-rose-50"}`}>
                          {simulatedRole !== "guest" ? "✔ ALLOW" : "❌ DENY"}
                        </span>
                      </div>
                      <div className="mt-1 flex items-center justify-between text-xs font-mono">
                        <span>Write API</span>
                        <span className={`px-2 py-0.5 font-bold ${simulatedRole === "faculty" ? "text-emerald-700 bg-emerald-50" : "text-rose-700 bg-rose-50"}`}>
                          {simulatedRole === "faculty" ? "✔ ALLOW" : "❌ DENY"}
                        </span>
                      </div>
                    </div>

                    <div className="p-3 border border-black bg-white">
                      <span className="text-[10px] font-mono font-bold text-slate-400">TARGET: /users/</span>
                      <div className="mt-1 flex items-center justify-between text-xs font-mono">
                        <span>Read User</span>
                        <span className={`px-2 py-0.5 font-bold ${simulatedRole !== "guest" ? "text-emerald-700 bg-emerald-50" : "text-rose-700 bg-rose-50"}`}>
                          {simulatedRole !== "guest" ? "✔ ALLOW" : "❌ DENY"}
                        </span>
                      </div>
                      <div className="mt-1 flex items-center justify-between text-xs font-mono">
                        <span>Write Role</span>
                        <span className="px-2 py-0.5 font-bold text-rose-700 bg-rose-50">
                          ❌ DENY ALL
                        </span>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
